# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
  platform :ios, '16.4'

  
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  
#  pod 'JGProgressHUD'
  pod 'RealmSwift'
  pod 'SDWebImage', '~> 5.0'
  pod 'MessageKit'

  # Pods for ChatApp

end
